# Generated by Django 4.2 on 2023-05-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('importer', '0001_initial'), ('importer', '0002_assetdetails_kupot_reports_remove_report_company_and_more'), ('importer', '0003_remove_reports_category_remove_reports_fair_value_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('track_number', models.CharField(max_length=255)),
                ('track_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('kupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.kupot')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('stock_name', models.CharField(max_length=255)),
                ('stock_code', models.IntegerField()),
                ('issuer_code', models.IntegerField()),
                ('stock_exchange', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('rater', models.CharField(max_length=50)),
                ('purcahse_date', models.DateField()),
                ('average_life_span', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('interest_rate', models.FloatField()),
                ('proceeds', models.FloatField()),
                ('value', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('interest_dividend', models.FloatField()),
                ('market_value', models.FloatField()),
                ('percent_of_value', models.FloatField()),
                ('percent_of_asset_channel', models.FloatField()),
                ('percent_of_total_assets', models.FloatField()),
                ('info_provider', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('base_asset', models.CharField(max_length=100)),
                ('fair_value', models.FloatField()),
                ('consortium', models.BooleanField()),
                ('last_valuation_date', models.DateField()),
                ('roi_in_period', models.FloatField()),
                ('estimated_value', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.reports')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('fair_value', models.FloatField()),
                ('percent_of_total', models.FloatField()),
                ('kupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.kupot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.reports')),
            ],
        ),
    ]
