# Generated by Django 4.2 on 2023-05-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_assetdetails_kupot_reports_remove_report_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='fair_value',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='percent_of_total',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('fair_value', models.FloatField()),
                ('percent_of_total', models.FloatField()),
                ('kupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.kupot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.reports')),
            ],
        ),
    ]
