# Generated by Django 4.2 on 2023-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_squashed_0003_remove_reports_category_remove_reports_fair_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='average_life_span',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='base_asset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='consortium',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='estimated_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='exchange_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='fair_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='info_provider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='interest_dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='interest_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='issuer_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='last_valuation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='market_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='percent_of_asset_channel',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='percent_of_total_assets',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='percent_of_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='proceeds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='purcahse_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='rater',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='roi_in_period',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='stock_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='stock_exchange',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kupot',
            name='track_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
