# Generated by Django 4.2 on 2023-06-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_assetdetails_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdetails',
            old_name='report_id',
            new_name='report',
        ),
    ]
