# Generated by Django 4.2 on 2023-06-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_reports_file_name_reports_ingested_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdetails',
            old_name='report',
            new_name='reports',
        ),
    ]
