# Generated by Django 4.2 on 2023-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_alter_assetdetails_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesNotIngested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UnmappedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('tab_name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reports',
            name='ingested_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
