# Generated by Django 4.2 on 2023-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0009_filesnotingested_unmappedfields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='consortium',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
