# Generated by Django 4.2 on 2023-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0010_alter_assetdetails_consortium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='issuer_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
