# Generated by Django 4.2 on 2024-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0011_alter_assetdetails_issuer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='average_interest_rate',
            field=models.FloatField(null=True),
        ),
    ]
