# Generated by Django 4.2 on 2024-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0012_assetdetails_average_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='asset_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='commitment',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='commitment_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='coordinated_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='effective_interest',
            field=models.FloatField(null=True),
        ),
    ]
